version: "3.7"

services:
  flask:
    build:
      context: ./services/flask
      dockerfile: Dockerfile
    volumes:
      - "./services/flask:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@flask-db:5432/flask_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@flask-db:5432/flask_test
    depends_on:
      - flask-db

  flask-db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_FLASK_SERVICE_URL=${REACT_APP_FLASK_SERVICE_URL}
    depends_on:
      - flask
