version: "3.7"

services:
  flask:
    build:
      context: ./services/flask
      dockerfile: Dockerfile-prod
    ports:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - flask-db

  flask-db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_FLASK_SERVICE_URL=${REACT_APP_FLASK_SERVICE_URL}
    ports:
      - "3007:80"
    depends_on:
      - flask
